services:
  backend1:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - proxy-backend
      - backend-postgre
      - prometheus_backend
  backend2:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - proxy-backend
      - backend-postgre
      - prometheus_backend
  backend3:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - proxy-backend
      - backend-postgre
      - prometheus_backend
  postgre:
    image: postgres:16-alpine
    env_file:
      - ./postgre.env
    networks:
      - backend-postgre
    volumes:
      - postgre-data:/var/lib/postgresql/data
  proxy:
    image: nginx:stable
    networks:
      - proxy-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  prometheus:
    image: prom/prometheus
    networks:
      - prometheus_backend
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090  
  #grafana:

networks:
  proxy-backend:
  backend-postgre:
  prometheus_backend:
volumes:
  postgre-data:
  prometheus_data: