services:
  backend1:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - proxy-backend
      - backend-postgre
  backend2:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - proxy-backend
      - backend-postgre
  backend3:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - proxy-backend
      - backend-postgre
  postgre:
    image: postgres:16-alpine
    env_file:
      - ./postgre.env
    networks:
      - backend-postgre
    volumes:
      - postgre-data:/var/lib/postgresql/data
  proxy:
    image: nginx:stable
    networks:
      - proxy-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  #prometheus:
  #grafana:

networks:
  proxy-backend:
  backend-postgre:
volumes:
  postgre-data: